package GUI;

import DTO.CitaNuevoDTO;
import Entidades.Usuario;
import Exception.NegocioException;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 * Frame Principal. Tiene un cardLayout para cambiar a todas las pantallas
 * necesarias.
 *
 * @author Sebastian Moreno
 */
public class FramePrincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;

    //Pantallas
    pantallaInicioSesion pantallaInicioSesion;
    pantallaRegistro pantallaRegistro;
    pantallaMenuPrincipalPacientes pantallaPacientes;
    pantallaInformacionUsuario pantallaInformacionUsuarios;
    pantallaTusConsultas pantallaTusConsultas;
    pantallaMedicosMenu pantallaMedicosMenu;
    pantallaCitasPendientes pantallaCitasPendientes;
    pantallaConsultasPacientes pantallaConsultasPacientes;
    pantallaAgendarCita pantallaAgendarCita;
    pantallaDatosConsulta pantallaDatosConsulta;
    pantallaInformacionCita pantallaInformacionCita;
    pantallaInformacionCitaEmergencia pantallaInformacionCitaEmergencia;
    pantallaFolio pantallaFolio;
    //Pantallas

    private Usuario usuarioAutenticado;
    private CitaNuevoDTO citaFinal;

    /**
     * Constructor del Frame Principal. Inicializa el frame, establece su
     * tamaño, comportamiento al cerrar, ubicación y componentes.
     *
     * @throws NegocioException Si ocurre un error en la lógica de negocio
     * durante la inicialización.
     * @throws SQLException Si ocurre un error durante la inicialización de la
     * base de datos.
     */
    public FramePrincipal() throws NegocioException, SQLException {
        setTitle("Sistema clinica");
        setSize(1000, 700);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();

        inicializarPantallas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));

        panelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    /* METODOS DE APOYO EN FRAME PRINCIPAL*/
    /**
     * Inicializa las pantallas y las agrega al CardLayout.
     *
     * @throws NegocioException Si ocurre un error en la lógica de negocio
     * durante la inicialización de las pantallas.
     * @throws SQLException Si ocurre un error durante la inicialización de las
     * pantallas (ej. conexión a la BD).
     */
    public void inicializarPantallas() throws NegocioException, SQLException {
        cardLayout = new CardLayout();
        panelPrincipal.setLayout(cardLayout);
        pantallaInicioSesion = new pantallaInicioSesion(this);
        pantallaRegistro = new pantallaRegistro(this);
        pantallaPacientes = new pantallaMenuPrincipalPacientes(this);
        pantallaInformacionUsuarios = new pantallaInformacionUsuario(this);
        pantallaTusConsultas = new pantallaTusConsultas(this);
        pantallaMedicosMenu = new pantallaMedicosMenu(this);
        pantallaCitasPendientes = new pantallaCitasPendientes(this);
        pantallaConsultasPacientes = new pantallaConsultasPacientes(this);
        pantallaAgendarCita = new pantallaAgendarCita(this);
        pantallaDatosConsulta = new pantallaDatosConsulta(this);
        pantallaInformacionCita = new pantallaInformacionCita(this);
        pantallaInformacionCitaEmergencia = new pantallaInformacionCitaEmergencia(this);
        pantallaFolio = new pantallaFolio(this);

        panelPrincipal.add(pantallaInicioSesion, "pantallaInicioSesion");
        panelPrincipal.add(pantallaRegistro, "pantallaRegistro");
        panelPrincipal.add(pantallaPacientes, "pantallaPacientes");
        panelPrincipal.add(pantallaInformacionUsuarios, "pantallaInformacionUsuarios");
        panelPrincipal.add(pantallaTusConsultas, "pantallaTusConsultas");
        panelPrincipal.add(pantallaMedicosMenu, "pantallaMedicosMenu");
        panelPrincipal.add(pantallaCitasPendientes, "pantallaCitasPendientes");
        panelPrincipal.add(pantallaConsultasPacientes, "pantallaConsultasPacientes");
        panelPrincipal.add(pantallaAgendarCita, "pantallaAgendarCita");
        panelPrincipal.add(pantallaDatosConsulta, "pantallaDatosConsulta");
        panelPrincipal.add(pantallaInformacionCita, "pantallaInformacionCita");
        panelPrincipal.add(pantallaInformacionCitaEmergencia, "pantallaInformacionCitaEmergencia");
        panelPrincipal.add(pantallaFolio, "pantallaFolio");

        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    /**
     * Cambia el panel visible en el CardLayout.
     *
     * @param nombrePanel El nombre del panel que se va a mostrar. Debe
     * coincidir con la clave usada al agregar el panel al CardLayout.
     */
    public void cambiarPanel(String nombrePanel) {
        cardLayout.show(panelPrincipal, nombrePanel);
    }

    /**
     * Establece el usuario autenticado en el Frame Principal.
     *
     * @param usuario El usuario autenticado.
     */
    public void setUsuarioAutenticado(Usuario usuario) {
        this.usuarioAutenticado = usuario;
    }

    /**
     * Obtiene el usuario autenticado en el Frame Principal.
     *
     * @return El usuario autenticado.
     */
    public Usuario getUsuarioAutenticado() {
        return usuarioAutenticado;
    }

    /**
     * Establece la cita final.
     *
     * @param citaFinal La cita final.
     */
    public void setCitaFinal(CitaNuevoDTO citaFinal) {
        this.citaFinal = citaFinal;
    }

    /**
     * Obtiene la cita final.
     *
     * @return La cita final.
     */
    public CitaNuevoDTO getCitaFinal() {
        return citaFinal;
    }

    // Getters para las pantallas (Getters for the screens)
    /**
     * Obtiene la pantalla del menú de médicos.
     *
     * @return La pantalla del menú de médicos.
     */
    public pantallaMedicosMenu getPantallaMedicosMenu() {
        return pantallaMedicosMenu;
    }

    /**
     * Obtiene la pantalla de información del usuario.
     *
     * @return La pantalla de información del usuario.
     */
    public pantallaInformacionUsuario getPantallaInformacion() {
        return pantallaInformacionUsuarios;
    }

    /**
     * Obtiene la pantalla de citas pendientes.
     *
     * @return La pantalla de citas pendientes.
     */
    public pantallaCitasPendientes getPantallaCitasPendientes() {
        return pantallaCitasPendientes;
    }

    /**
     * Obtiene la pantalla de información de citas.
     *
     * @return La pantalla de información de citas.
     */
    public pantallaInformacionCita getPantallaInformacionCitas() {
        return pantallaInformacionCita;
    }

    /**
     * Obtiene la pantalla para agendar citas.
     *
     * @return La pantalla para agendar citas.
     */
    public pantallaAgendarCita getPantallaAgendarCita() {
        return pantallaAgendarCita;
    }

    /**
     * Obtiene la pantalla principal de pacientes.
     *
     * @return La pantalla principal de pacientes.
     */
    public pantallaMenuPrincipalPacientes getPantallaPacientes() {
        return pantallaPacientes;
    }

    /**
     * Obtiene la pantalla de información de citas de emergencia.
     *
     * @return La pantalla de información de citas de emergencia.
     */
    public pantallaInformacionCitaEmergencia getPantallaInformacionCitaEmergencia() {
        return pantallaInformacionCitaEmergencia;
    }

    /**
     * Obtiene la pantalla de datos de consulta.
     *
     * @return La pantalla de datos de consulta.
     */
    public pantallaDatosConsulta getPantallaDatosConsulta() {
        return pantallaDatosConsulta;
    }

    /**
     * Obtiene la pantalla de tus consultas.
     *
     * @return La pantalla de tus consultas.
     */
    public pantallaTusConsultas getPantallaTusConsultas() {
        return pantallaTusConsultas;
    }
}
