/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BO.Direccion_PacienteBO;
import BO.PacienteBO;
import BO.UsuarioBO;
import configuracion.DependencyInjector;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian Moreno
 */
public class pantallaMedicosMenu extends javax.swing.JPanel {

    /**
     * Creates new form pantallaMedicosMenu
     */
    private UsuarioBO usuarioBO = DependencyInjector.crearUsuarioBO();
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private Direccion_PacienteBO direccionBO = DependencyInjector.crearDireccionBO();
    private FramePrincipal framePrincipal;

    public pantallaMedicosMenu(FramePrincipal frame) {
        this.framePrincipal = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSubTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlConsultarHistorialPaciente = new javax.swing.JPanel();
        btnAgendarCita = new javax.swing.JLabel();
        pnlAgendarCita1 = new javax.swing.JPanel();
        btnAgendarCita1 = new javax.swing.JLabel();
        pnlActivo = new javax.swing.JPanel();
        btnAgendarCita3 = new javax.swing.JLabel();
        pnlInactivo = new javax.swing.JPanel();
        btnAgendarCita2 = new javax.swing.JLabel();
        pnlInactivo1 = new javax.swing.JPanel();
        btnAgendarCita4 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtActivo = new javax.swing.JLabel();
        txtInactivo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        txtSubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtSubTitulo.setText("Menú Principal");
        add(txtSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MEDICOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 103, -1, -1));

        pnlConsultarHistorialPaciente.setBackground(new java.awt.Color(60, 109, 232));

        btnAgendarCita.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgendarCita.setText("Consultar Historial Paciente");
        btnAgendarCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlConsultarHistorialPacienteLayout = new javax.swing.GroupLayout(pnlConsultarHistorialPaciente);
        pnlConsultarHistorialPaciente.setLayout(pnlConsultarHistorialPacienteLayout);
        pnlConsultarHistorialPacienteLayout.setHorizontalGroup(
            pnlConsultarHistorialPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarHistorialPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultarHistorialPacienteLayout.setVerticalGroup(
            pnlConsultarHistorialPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarHistorialPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlConsultarHistorialPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 193, -1, -1));

        pnlAgendarCita1.setBackground(new java.awt.Color(255, 0, 0));

        btnAgendarCita1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgendarCita1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgendarCita1.setText("Consultar Agenda");
        btnAgendarCita1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlAgendarCita1Layout = new javax.swing.GroupLayout(pnlAgendarCita1);
        pnlAgendarCita1.setLayout(pnlAgendarCita1Layout);
        pnlAgendarCita1Layout.setHorizontalGroup(
            pnlAgendarCita1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendarCita1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgendarCita1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAgendarCita1Layout.setVerticalGroup(
            pnlAgendarCita1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendarCita1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlAgendarCita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 193, -1, -1));

        pnlActivo.setBackground(new java.awt.Color(0, 204, 0));

        btnAgendarCita3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgendarCita3.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgendarCita3.setText("Médico Activo");
        btnAgendarCita3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlActivoLayout = new javax.swing.GroupLayout(pnlActivo);
        pnlActivo.setLayout(pnlActivoLayout);
        pnlActivoLayout.setHorizontalGroup(
            pnlActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgendarCita3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlActivoLayout.setVerticalGroup(
            pnlActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 467, -1, -1));

        pnlInactivo.setBackground(new java.awt.Color(255, 51, 51));

        btnAgendarCita2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btnAgendarCita2.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgendarCita2.setText("Médico Inactivo");
        btnAgendarCita2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendarCita2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendarCita2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlInactivoLayout = new javax.swing.GroupLayout(pnlInactivo);
        pnlInactivo.setLayout(pnlInactivoLayout);
        pnlInactivoLayout.setHorizontalGroup(
            pnlInactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInactivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgendarCita2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlInactivoLayout.setVerticalGroup(
            pnlInactivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInactivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 402, -1, -1));

        pnlInactivo1.setBackground(new java.awt.Color(255, 51, 51));

        btnAgendarCita4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAgendarCita4.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgendarCita4.setText("Cerrar Sesión");
        btnAgendarCita4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgendarCita4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendarCita4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlInactivo1Layout = new javax.swing.GroupLayout(pnlInactivo1);
        pnlInactivo1.setLayout(pnlInactivo1Layout);
        pnlInactivo1Layout.setHorizontalGroup(
            pnlInactivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInactivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita4, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInactivo1Layout.setVerticalGroup(
            pnlInactivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInactivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarCita4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlInactivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 467, -1, -1));

        txtStatus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(0, 0, 0));
        txtStatus.setText("Status:");
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        txtActivo.setForeground(new java.awt.Color(51, 153, 0));
        txtActivo.setText("ACTIVO");
        add(txtActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, 50, -1));

        txtInactivo.setForeground(new java.awt.Color(255, 0, 0));
        txtInactivo.setText("INACTIVO");
        add(txtInactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 129, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarCita4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarCita4MouseClicked
        framePrincipal.cambiarPanel("pantallaInicioSesion");
    }//GEN-LAST:event_btnAgendarCita4MouseClicked

    private void btnAgendarCita2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarCita2MouseClicked
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro de continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            System.out.println("El usuario seleccionó Sí.");

        } else {
            System.out.println("El usuario seleccionó No.");
        }
    }//GEN-LAST:event_btnAgendarCita2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgendarCita;
    private javax.swing.JLabel btnAgendarCita1;
    private javax.swing.JLabel btnAgendarCita2;
    private javax.swing.JLabel btnAgendarCita3;
    private javax.swing.JLabel btnAgendarCita4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlActivo;
    private javax.swing.JPanel pnlAgendarCita1;
    private javax.swing.JPanel pnlConsultarHistorialPaciente;
    private javax.swing.JPanel pnlInactivo;
    private javax.swing.JPanel pnlInactivo1;
    private javax.swing.JLabel txtActivo;
    private javax.swing.JLabel txtInactivo;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtSubTitulo;
    // End of variables declaration//GEN-END:variables
}
