
package GUI;

/**
 * Pantalla tu información.
 * @author Sebastian Moreno
 */
public class pantallaInformacionUsuario extends javax.swing.JPanel {

    public pantallaInformacionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSubTitulo = new javax.swing.JLabel();
        txtTituloPantalla = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtCelular = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JLabel();
        txtColonia = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtNumeroExt = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JTextField();
        inputUsuario = new javax.swing.JTextField();
        inputContraseña = new javax.swing.JTextField();
        inputCalle = new javax.swing.JTextField();
        inputNumExt = new javax.swing.JTextField();
        inputColonia = new javax.swing.JTextField();
        inputCodigoPostal = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputApellidoP = new javax.swing.JTextField();
        inputCelular = new javax.swing.JTextField();
        inputApellidoM = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        txtSubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtSubTitulo.setText("Tu Información");
        add(txtSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        txtTituloPantalla.setFont(new java.awt.Font("Roboto", 1, 44)); // NOI18N
        txtTituloPantalla.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloPantalla.setText("Registro Médico");
        add(txtTituloPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtCodigoPostal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCodigoPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoPostal.setText("Codigo Postal*:");
        add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre(s)*:");
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtApellidoP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoP.setText("Apellido Paterno*:");
        add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        txtApellidoM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoM.setText("Apellido Materno (Opcional):");
        add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setText("Usuario*:");
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        txtCelular.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        txtCelular.setText("Fecha de Nacimiento*:");
        add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        txtCorreoElectronico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoElectronico.setText("Correo Electronico*:");
        add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtColonia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtColonia.setForeground(new java.awt.Color(0, 0, 0));
        txtColonia.setText("Colonia*:");
        add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        txtContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setText("Contraseña*:");
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        txtCalle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle*:");
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        txtNumeroExt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNumeroExt.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroExt.setText("Numero Ext*:");
        add(txtNumeroExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        inputCorreo.setBorder(null);
        add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, 40));

        inputUsuario.setBorder(null);
        add(inputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 260, 40));

        inputContraseña.setBorder(null);
        add(inputContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 260, 40));

        inputCalle.setBorder(null);
        add(inputCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 200, 40));

        inputNumExt.setBorder(null);
        add(inputNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 110, 40));

        inputColonia.setBorder(null);
        add(inputColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 40));

        inputCodigoPostal.setBorder(null);
        add(inputCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 200, 40));

        inputNombre.setBorder(null);
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 40));

        inputApellidoP.setBorder(null);
        add(inputApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, 40));

        inputCelular.setBorder(null);
        add(inputCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 200, 40));

        inputApellidoM.setBorder(null);
        add(inputApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 230, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputApellidoM;
    private javax.swing.JTextField inputApellidoP;
    private javax.swing.JTextField inputCalle;
    private javax.swing.JTextField inputCelular;
    private javax.swing.JTextField inputCodigoPostal;
    private javax.swing.JTextField inputColonia;
    private javax.swing.JTextField inputContraseña;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNumExt;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel txtApellidoM;
    private javax.swing.JLabel txtApellidoP;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCelular;
    private javax.swing.JLabel txtCodigoPostal;
    private javax.swing.JLabel txtColonia;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtCorreoElectronico;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNumeroExt;
    private javax.swing.JLabel txtSubTitulo;
    private javax.swing.JLabel txtTituloPantalla;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
