package GUI;

import BO.Direccion_PacienteBO;
import BO.PacienteBO;
import BO.UsuarioBO;
import DTO.Direccion_PacienteNuevaDTO;
import DTO.PacienteNuevoDTO;
import Entidades.Direccion_Paciente;
import Entidades.Paciente;
import Exception.NegocioException;
import Exception.PersistenciaException;
import com.toedter.calendar.JDateChooser;
import configuracion.DependencyInjector;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Pantalla tu información.
 *
 * @author Sebastian Moreno
 */
public class pantallaInformacionUsuario extends javax.swing.JPanel {
    private UsuarioBO usuarioBO = DependencyInjector.crearUsuarioBO();
    private PacienteBO pacienteBO = DependencyInjector.crearPacienteBO();
    private Direccion_PacienteBO direccionBO = DependencyInjector.crearDireccionBO();
    private JDateChooser selectorFechas;
    private FramePrincipal framePrincipal;
    pantallaInicioSesion pantalla = new pantallaInicioSesion(framePrincipal);
    
    public pantallaInformacionUsuario(FramePrincipal frame) {
        this.framePrincipal = frame;
        selectorFechas = new JDateChooser();
        selectorFechas.setBounds(610, 285, 200, 40);
        this.add(selectorFechas);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSubTitulo = new javax.swing.JLabel();
        txtTituloPantalla = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JLabel();
        txtColonia = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtNumeroExt = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JTextField();
        inputCalle = new javax.swing.JTextField();
        inputNumExt = new javax.swing.JTextField();
        inputColonia = new javax.swing.JTextField();
        inputCodigoPostal = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputApellidoP = new javax.swing.JTextField();
        inputCelular = new javax.swing.JTextField();
        inputApellidoM = new javax.swing.JTextField();
        pnlRestablecerDatos = new javax.swing.JPanel();
        btnRestablecer = new javax.swing.JLabel();
        pnlBotonGuardar1 = new javax.swing.JPanel();
        btnGuardar1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        txtSubTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtSubTitulo.setText("Tu Información");
        add(txtSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        txtTituloPantalla.setFont(new java.awt.Font("Roboto", 1, 44)); // NOI18N
        txtTituloPantalla.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloPantalla.setText("Registro Médico");
        add(txtTituloPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtCodigoPostal.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCodigoPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoPostal.setText("Codigo Postal*:");
        add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre(s)*:");
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtApellidoP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoP.setText("Apellido Paterno*:");
        add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        txtApellidoM.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoM.setText("Apellido Materno (Opcional):");
        add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        txtFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setText("Celular*:");
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        txtCorreoElectronico.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoElectronico.setText("Correo Electronico*:");
        add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtColonia.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtColonia.setForeground(new java.awt.Color(0, 0, 0));
        txtColonia.setText("Colonia*:");
        add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        txtCalle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle*:");
        add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        txtNumeroExt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtNumeroExt.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroExt.setText("Numero Ext*:");
        add(txtNumeroExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        inputCorreo.setBorder(null);
        add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, 40));

        inputCalle.setBorder(null);
        add(inputCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 200, 40));

        inputNumExt.setBorder(null);
        add(inputNumExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 110, 40));

        inputColonia.setBorder(null);
        add(inputColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 40));

        inputCodigoPostal.setBorder(null);
        add(inputCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 200, 40));

        inputNombre.setBorder(null);
        add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 40));

        inputApellidoP.setBorder(null);
        add(inputApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, 40));

        inputCelular.setBorder(null);
        add(inputCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 200, 40));

        inputApellidoM.setBorder(null);
        add(inputApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 230, 40));

        pnlRestablecerDatos.setBackground(new java.awt.Color(255, 102, 102));
        pnlRestablecerDatos.setForeground(new java.awt.Color(0, 0, 0));
        pnlRestablecerDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRestablecerDatosMouseClicked(evt);
            }
        });

        btnRestablecer.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnRestablecer.setForeground(new java.awt.Color(255, 255, 255));
        btnRestablecer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRestablecer.setText("Restablecer datos");
        btnRestablecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestablecer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestablecerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlRestablecerDatosLayout = new javax.swing.GroupLayout(pnlRestablecerDatos);
        pnlRestablecerDatos.setLayout(pnlRestablecerDatosLayout);
        pnlRestablecerDatosLayout.setHorizontalGroup(
            pnlRestablecerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(pnlRestablecerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRestablecerDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlRestablecerDatosLayout.setVerticalGroup(
            pnlRestablecerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(pnlRestablecerDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRestablecerDatosLayout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        add(pnlRestablecerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 340, 40));

        pnlBotonGuardar1.setBackground(new java.awt.Color(0, 123, 255));
        pnlBotonGuardar1.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar1.setText("Guardar Cambios");
        btnGuardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonGuardar1Layout = new javax.swing.GroupLayout(pnlBotonGuardar1);
        pnlBotonGuardar1.setLayout(pnlBotonGuardar1Layout);
        pnlBotonGuardar1Layout.setHorizontalGroup(
            pnlBotonGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
            .addGroup(pnlBotonGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBotonGuardar1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlBotonGuardar1Layout.setVerticalGroup(
            pnlBotonGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlBotonGuardar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBotonGuardar1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(pnlBotonGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 330, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras (1).png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtFecha1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtFecha1.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha1.setText("Fecha de Nacimiento*:");
        add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestablecerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestablecerMouseClicked
        try {
            cargarPaciente();
        } catch (PersistenciaException ex) {
            Logger.getLogger(pantallaInformacionUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestablecerMouseClicked

    private void btnGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardar1MouseClicked
        try {
            actualizarPaciente();
        } catch (NegocioException ex) {
            Logger.getLogger(pantallaInformacionUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardar1MouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        framePrincipal.cambiarPanel("pantallaPacientes");
        System.out.println(framePrincipal.getUsuarioAutenticado());
    }//GEN-LAST:event_btnVolverMouseClicked

    private void pnlRestablecerDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRestablecerDatosMouseClicked
        
    }//GEN-LAST:event_pnlRestablecerDatosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar1;
    private javax.swing.JLabel btnRestablecer;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JTextField inputApellidoM;
    private javax.swing.JTextField inputApellidoP;
    private javax.swing.JTextField inputCalle;
    private javax.swing.JTextField inputCelular;
    private javax.swing.JTextField inputCodigoPostal;
    private javax.swing.JTextField inputColonia;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNumExt;
    private javax.swing.JPanel pnlBotonGuardar1;
    private javax.swing.JPanel pnlRestablecerDatos;
    private javax.swing.JLabel txtApellidoM;
    private javax.swing.JLabel txtApellidoP;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCodigoPostal;
    private javax.swing.JLabel txtColonia;
    private javax.swing.JLabel txtCorreoElectronico;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtFecha1;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNumeroExt;
    private javax.swing.JLabel txtSubTitulo;
    private javax.swing.JLabel txtTituloPantalla;
    // End of variables declaration//GEN-END:variables

public void cargarPaciente() throws PersistenciaException{
    Paciente pacienteConsultado =  pacienteBO.buscarPacientePorID(framePrincipal.getUsuarioAutenticado().getIdUsuario());
    
       if (pacienteConsultado != null) {
        // Datos personales del paciente
        inputNombre.setText(pacienteConsultado.getNombre());
        inputApellidoM.setText(pacienteConsultado.getApellidoMaterno());
        inputApellidoP.setText(pacienteConsultado.getApellidoPaterno());
        inputCorreo.setText(pacienteConsultado.getCorreo());
        inputCelular.setText(pacienteConsultado.getTelefono());
 
        // Datos de la dirección 
        inputCalle.setText(pacienteConsultado.getDireccion().getCalle());
        inputColonia.setText(pacienteConsultado.getDireccion().getColonia());
        inputCodigoPostal.setText(String.valueOf(pacienteConsultado.getDireccion().getCp()));
        inputNumExt.setText(pacienteConsultado.getDireccion().getNumero());
        LocalDate fechaNacimiento = pacienteConsultado.getFechaNacimiento();
        Date date = Date.from(fechaNacimiento.atStartOfDay(ZoneId.systemDefault()).toInstant());
        selectorFechas.setDate(date);
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró información del paciente.", "Error", JOptionPane.ERROR_MESSAGE);
        
    }
}
public void actualizarPaciente() throws NegocioException {
    try {
        // Obtener el ID del usuario autenticado
        int id = framePrincipal.getUsuarioAutenticado().getIdUsuario();

        // Obtener la información de los inputs
        String nombre = inputNombre.getText().trim();
        String apellidoP = inputApellidoP.getText().trim();
        String apellidoM = inputApellidoM.getText().trim();
        String correo = inputCorreo.getText().trim();
        String celular = inputCelular.getText().trim();
        String calle = inputCalle.getText().trim();
        String colonia = inputColonia.getText().trim();
        String numero = inputNumExt.getText().trim();
        int codigoPostal = Integer.parseInt(inputCodigoPostal.getText().trim());

        // Obtener la fecha seleccionada en JDateChooser y convertirla a LocalDate
        Date fechaSeleccionada = selectorFechas.getDate();
        LocalDate fechaNacimiento = fechaSeleccionada.toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();

        // Crear objeto Direccion
        Direccion_Paciente direccion = new Direccion_Paciente(calle, colonia,codigoPostal,numero);

        // Crear objeto Paciente con los datos actualizados
        PacienteNuevoDTO pacienteActualizado = new PacienteNuevoDTO(framePrincipal.getUsuarioAutenticado(),direccion, nombre, apellidoP, apellidoM, correo,fechaNacimiento,celular);
        // Llamar a la capa de negocio para actualizar los datos
        pacienteBO.actualizarPaciente(id, pacienteActualizado);

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "Paciente actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Error: Código postal debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NullPointerException e) {
        JOptionPane.showMessageDialog(null, "Error: Por favor, seleccione una fecha válida.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (PersistenciaException e) {
        JOptionPane.showMessageDialog(null, "Error al actualizar el paciente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

}

